# Generated by Django 4.1.5 on 2023-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userstate',
            new_name='user_state',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usertype',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='viewlevel',
            new_name='view_level',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
