# Generated by Django 4.1.5 on 2023-01-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0002_rename_userid_users_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(default='1.01.2000'),
        ),
    ]
