# Generated by Django 4.1.5 on 2023-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0007_alter_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
