# Generated by Django 4.1.5 on 2023-01-08 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0008_alter_users_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
