# Generated by Django 4.1.5 on 2023-01-08 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0009_remove_users_dob_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
