# Generated by Django 4.1.5 on 2023-01-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mir1', '0010_alter_users_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
    ]
