# Generated by Django 4.1.5 on 2023-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('state_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=10)),
                ('profit_amount', models.CharField(max_length=20)),
            ],
        ),
    ]
