# Generated by Django 4.1.5 on 2023-01-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reports',
            new_name='benefits',
        ),
    ]
