# Generated by Django 4.1.5 on 2023-01-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_benefits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefits',
            old_name='profit_amount',
            new_name='profit_amt',
        ),
    ]
