# Generated by Django 4.1.5 on 2023-01-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_profit_amount_benefits_profit_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('state_ida', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_namea', models.CharField(max_length=20)),
                ('area_target', models.IntegerField()),
                ('area_saved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_ids', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_names', models.CharField(max_length=20)),
                ('cum_budget', models.IntegerField()),
                ('achieved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('state_idw', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_namew', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('litres_prov', models.IntegerField()),
                ('litres_benefit', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='benefits',
            old_name='state_id',
            new_name='state_idb',
        ),
        migrations.RenameField(
            model_name='benefits',
            old_name='state_name',
            new_name='state_nameb',
        ),
    ]
