# Generated by Django 4.1.5 on 2023-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_area_state_water_rename_state_id_benefits_state_idb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='achieved',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='state',
            name='cum_budget',
            field=models.CharField(max_length=7),
        ),
    ]
